// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/23/2025, 4:34:40 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/volkanoluc/Projects/eneba/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/volkanoluc/Projects/eneba/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/volkanoluc/Projects/eneba/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/volkanoluc/Projects/eneba/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/volkanoluc/Projects/eneba/frontend/plugins/**/*.{js,ts,mjs}","/Users/volkanoluc/Projects/eneba/frontend/composables/**/*.{js,ts,mjs}","/Users/volkanoluc/Projects/eneba/frontend/utils/**/*.{js,ts,mjs}","/Users/volkanoluc/Projects/eneba/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/volkanoluc/Projects/eneba/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/volkanoluc/Projects/eneba/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/volkanoluc/Projects/eneba/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;